name: Nightly integration test
on:
  push:
    branch: feature/integration-test-slack
  #schedule:
    # Run every day at 0 minutes and 0 hours (midnight GMT)
    #- cron: '0 0 * * *'
jobs:
  nightly-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
      - name: Report failure to slack
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: cadence-docs
          SLACK_MESSAGE: 'Nightly integration test has failed.'
          SLACK_TITLE: cadence-docs integration test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
